export const SP_AVAX_ABI = [
  // Read functions
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function totalPooledAVAX() view returns (uint256)",
  "function getExchangeRate() view returns (uint256)",
  "function previewStake(uint256) view returns (uint256)",
  "function previewUnlock(uint256) view returns (uint256)",
  "function getUnlockRequestCount(address) view returns (uint256)",
  "function getUnlockRequest(address, uint256) view returns (uint256 spAvaxAmount, uint256 avaxAmount, uint256 unlockTime, uint256 expiryTime, bool isReady, bool isExpired)",
  "function getStats() view returns (uint256 totalStaked, uint256 totalShares, uint256 exchangeRate, uint256 liquidBalance, uint256 pendingValidatorFees, uint256 pendingDaoFees, uint256 pendingDevFees, uint256 validatorFee, uint256 daoFee, uint256 devFee)",
  "function minStakeAmount() view returns (uint256)",
  "function unlockPeriod() view returns (uint256)",
  "function claimWindow() view returns (uint256)",
  "function owner() view returns (address)",
  "function paused() view returns (bool)",
  
  // Write functions
  "function stake() payable returns (uint256)",
  "function requestUnlock(uint256) returns (uint256)",
  "function claimUnlock(uint256)",
  "function cancelUnlock(uint256)",
  "function claimExpired(uint256)",
  
  // Admin functions
  "function withdraw(uint256)",
  "function deposit() payable",
  "function addRewards(uint256)",
  "function collectValidatorFees()",
  "function collectDaoFees()",
  "function collectDevFees()",
  "function collectAllFees()",
  "function setFeeStructure(uint256, uint256, uint256)",
  "function setMinStakeAmount(uint256)",
  "function setUnlockPeriod(uint256)",
  "function setClaimWindow(uint256)",
  "function pause()",
  "function unpause()",
  
  // Events
  "event Staked(address indexed user, uint256 avaxAmount, uint256 spAvaxAmount)",
  "event UnlockRequested(address indexed user, uint256 spAvaxAmount, uint256 avaxAmount, uint256 unlockTime, uint256 expiryTime)",
  "event Unstaked(address indexed user, uint256 spAvaxAmount, uint256 avaxAmount)",
  "event UnlockCancelled(address indexed user, uint256 index, uint256 spAvaxAmount)",
  "event UnlockExpired(address indexed user, uint256 index, uint256 spAvaxAmount)",
  "event RewardsAdded(uint256 totalReward, uint256 userReward, uint256 validatorFee, uint256 daoFee, uint256 devFee)",
  "event Withdrawn(address indexed to, uint256 amount)",
  "event Deposited(address indexed from, uint256 amount)",
  "event ValidatorFeesCollected(address indexed to, uint256 amount)",
  "event DaoFeesCollected(address indexed to, uint256 amount)",
  "event DevFeesCollected(address indexed to, uint256 amount)",
] as const;
